### ISSUE TITLE
sbt.ResolveException: unresolved dependency com.hadoop.gplcompression#hadoop-lzo;0.4.16?

### ISSUE THREAD

**Issue by fsck-mount** [yamrcraft/etl-light#2]
Hi @yamrcraft , 
While building this, i'm getting the following error. To fix this, we added Twitter Repo to resolvers, like the following in `build.sbt` file.

`resolvers +=  "Twitter Maven" at "http://maven.twttr.com"`

Still getting the same error. 

Any idea how to fix?

Here is the stacktrace: 

```bash

[info] Resolving com.hadoop.gplcompression#hadoop-lzo;0.4.16 ...
[warn] 	module not found: com.hadoop.gplcompression#hadoop-lzo;0.4.16
[warn] ==== local: tried
[warn]   /Users/GowthamSai/.ivy2/local/com.hadoop.gplcompression/hadoop-lzo/0.4.16/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/hadoop/gplcompression/hadoop-lzo/0.4.16/hadoop-lzo-0.4.16.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.hadoop.gplcompression#hadoop-lzo;0.4.16: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.hadoop.gplcompression:hadoop-lzo:0.4.16
[warn] 		  +- com.twitter.elephantbird:elephant-bird-core:4.4
[warn] 		  +- org.apache.parquet:parquet-protobuf:1.9.0 (/Users/GowthamSai/Documents/repo/etl-light/project/Dependencies.scala#L6)
[warn] 		  +- yamrcraft:etlite_2.11:0.1.0
sbt.ResolveException: unresolved dependency: com.hadoop.gplcompression#hadoop-lzo;0.4.16: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)


	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (etlite/*:update) sbt.ResolveException: unresolved dependency: com.hadoop.gplcompression#hadoop-lzo;0.4.16: not found


```

**Comment by yamrcraft** [comment]
Hi @gowtham-sai ,
Thanks for submitting this issue, I pushed a fix, please verify it's working for you now.

**Comment by fsck-mount** [comment]
Hi @yamrcraft , 

It should work. I'll check and close the ticket. I missed that ThisBuild. 

Thanks :)

Just for Reference: f81ba8a86bcf3a4c129bf9ac5833f15e0db49cf0

**Comment by fsck-mount** [comment]
Hey @yamrcraft , it's working fine., Thanks for quick fix.  
Can you some examples for JSON to Parquet format?

**Comment by yamrcraft** [comment]
To convert a JSON to Parquet you'll need to define the schema of your messages which will then be used seamlessly to define the Parquet schema.

The way it is currently implemented is using JsonToParquetPipelineFactory  (see example at: etlite/src/main/resources/example_hdfs_application.conf).

JsonToParquetPipelineFactory uses a JsonToAvroTransformer in order to transform the JSON message into an avro GenericRecord, it needs a configuration ("schema-selection") which specifies a mapping between an event-type to its corresponding Avro schema or a default schema, it will first look for a field in the JSON message that is specified in "schema-selection.field" configuration and use the fetched value to get the corresponding schema from "schema-selection.schemas" configuration, if an entry is not found then a default schema specified in "default-schema-file" will be used.

Hope this helps.
